// Copie para ecosystem.config.js e preencha com suas chaves reais
// ecosystem.config.js está no .gitignore — nunca versione o arquivo com chaves

module.exports = {
    apps: [
        {
            name: "redis",
            script: "redis-server",
            args: "--save 60 1",
            autorestart: true,
            env: { PORT: 6379 },
        },
        {
            name: "core-backend",
            script: "services/core-backend/dist/index.js",
            cwd: "/home/SEU_USUARIO/Documentos/LaurinhaTTT",
            autorestart: true,
            max_restarts: 50,
            restart_delay: 5000,
            env: {
                NODE_ENV: "production",
                CORE_PORT: 3321,
                REDIS_URL: "redis://localhost:6379",
                DATABASE_URL: "postgresql://postgres:SENHA@localhost:5432/laurinha",
                LM_STUDIO_URL: "http://SEU_IP:1234/v1",
                LM_STUDIO_MODEL: "nome-do-modelo",
                OPENCODE_GO_API_KEY: "SUA_OPENCODE_API_KEY",
                OPENCODE_GO_MODEL: "deepseek-v4-flash",
                OPENCODE_GO_URL: "https://opencode.ai/zen/go/v1",
                AI_PROVIDER: "opencode-go",
                BRAVE_SEARCH_KEY: "SUA_BRAVE_SEARCH_KEY",
                RESEMBLE_API_KEY: "SUA_RESEMBLE_API_KEY",
                RESEMBLE_VOICE_UUID: "SEU_VOICE_UUID",
                OWNER_PLATFORM_ID: "SEU_NUMERO@c.us",
                OWNER_PLATFORM_IDS: "SEU_NUMERO@c.us,NUMERO_ALTERNATIVO@c.us",
                GEMINI_API_KEY: "SUA_GEMINI_API_KEY",
                GEMINI_MODEL: "gemini-2.0-flash-lite",
                PAGES_DIR: "/home/SEU_USUARIO/Documentos/LaurinhaTTT/public/pages",
                PAGES_BASE_URL: "https://SEU_DOMINIO",
                PROJECTS_DIR: "/home/SEU_USUARIO/Documentos/LaurinhaTTT/projects",
                NODE_MODULES_ROOT: "/home/SEU_USUARIO/Documentos/LaurinhaTTT/node_modules",
            },
        },
        {
            name: "api-router",
            script: "services/api-router/index.js",
            cwd: "/home/SEU_USUARIO/Documentos/LaurinhaTTT",
            autorestart: true,
            max_restarts: 50,
            restart_delay: 3000,
            watch: false,
            env: {
                NODE_ENV: "production",
                API_ROUTER_PORT: 3872,
                PROJECTS_DIR: "/home/SEU_USUARIO/Documentos/LaurinhaTTT/projects",
                NODE_PATH: "/home/SEU_USUARIO/Documentos/LaurinhaTTT/node_modules",
            },
        },
        {
            name: "pages-server",
            script: "pages-server.mjs",
            cwd: "/home/SEU_USUARIO/Documentos/LaurinhaTTT",
            autorestart: true,
            max_restarts: 50,
            restart_delay: 5000,
            env: {
                NODE_ENV: "production",
                PAGES_PORT: 3871,
                PAGES_DIR: "/home/SEU_USUARIO/Documentos/LaurinhaTTT/public/pages",
            },
        },
        {
            name: "dashboard",
            script: "build/index.js",
            cwd: "/home/SEU_USUARIO/Documentos/LaurinhaTTT/services/dashboard",
            autorestart: true,
            max_restarts: 50,
            restart_delay: 5000,
            env: {
                NODE_ENV: "production",
                PORT: 3323,
                REDIS_URL: "redis://localhost:6379",
                CORE_BACKEND_URL: "http://localhost:3321",
                WA_ADAPTER_URL: "http://localhost:3322",
                ORIGIN: "http://SEU_IP:3323",
            },
        },
    ],
};
